version: '3.7'

services:
#  app:
#    build: '.'
#    env_file:
#      - '.env'
#    ports:
#      - 8000:8000
#    depends_on:
#      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=application

volumes:
  postgres_data:
